title: Oryiman Ayaka
description: Ghostwriter
timezone: Africa/Lagos
permalink: /essays/:title/
newsletter_url: https://substack.com/@thehiddenlogic?utm_source=share&utm_medium=android&r=1ksn5l
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: essay
